run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    # Deprecated
    - exportloopref

    # Disabled purposely
    - exhaustruct # Does not make any sense
    - godox # Does not make any sense
    - depguard # Too boring to configure and maintain

linters-settings:
  varnamelen:
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request

issues:
  max-same-issues: 0
