run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    # Deprecated
    - tenv

    # Disabled purposely
    - exhaustruct # Does not make any sense
    - godox # Does not make any sense
    - depguard # Too boring to configure and maintain

linters-settings:
  varnamelen:
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
      - c *gin.Context
      - ok bool
      - kv jetstream.KeyValue
      - kv *nats.KV
      - kv KV
      - id string
      - wg *sync.WaitGroup
      - js jetstream.JetStream
      - i int

  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).Error

  wrapcheck:
    extra-ignore-sigs:
      - .Unpack(

  gochecknoglobals:


  revive:
    rules:
      - name: dot-imports
        disabled: true


issues:
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
