services:
  nats:
    image: nats:2.12
    labels:
      wtf.zhulik.fid.component: nats

    ports:
      - "4222:4222"
    volumes:
      - /tmp/nats/:/data
    command: [ "-js" ]

    networks:
      - nats

  start:
    image: ghcr.io/zhulik/fid
    labels:
      wtf.zhulik.fid.component: start

    command:
      - start
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./Fidfile.yaml:/Fidfile.yaml
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - nats

    restart: no

volumes:
  nats_data:

networks:
  nats:
    name: nats
    driver: bridge
