services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - /tmp/nats/:/data
    command: [ "-js" ]

  gateway:
    image: fid/gateway
    build:
      context: .
      args:
        COMPONENT: "gateway"
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "gateway"
    ports:
      - "8080:80"

  forwarder:
    image: fid/forwarder
    build:
      context: .
      args:
        COMPONENT: "forwarder"

    depends_on:
      - nats

    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "forwarder"

    ports:
      - "8081:80"

  infoserver:
    image: fid/infoserver
    build:
      context: .
      args:
        COMPONENT: "infoserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "infoserver"

    ports:
      - "8082:80"

  function:
    image: fid/demo-function
    build:
      context: .
      args:
        COMPONENT: "function"

    environment:
      - AWS_LAMBDA_RUNTIME_API=forwarder:80
      - FID_FUNCTION_NAME=function

    command: ["tail", "-f", "/dev/null"]

    labels:
      wtf.zhulik.fid.component: "function"
      wtf.zhulik.fid.scale.min: 3
      wtf.zhulik.fid.scale.max: 10
      wtf.zhulik.fid.timeout: 10

    deploy:
      labels:
        wtf.zhulik.fid.component: "function"
        wtf.zhulik.fid.scale.min: 3
        wtf.zhulik.fid.scale.max: 10
        wtf.zhulik.fid.timeout: 10

    depends_on:
      - forwarder


  not_a_function:
    image: nginx:latest

    environment:
      - SOME_VAR=1
      - SOME_OTHER_VAR="=1"
      - ANOTHER_VAR=

    labels:
      wtf.zhulik.fid.component: "function"
      wtf.zhulik.fid.scale.min: 3
      wtf.zhulik.fid.scale.max: 10
      wtf.zhulik.fid.timeout: 10

    deploy:
      labels:
        wtf.zhulik.fid.component: "function"
        wtf.zhulik.fid.scale.min: 3
        wtf.zhulik.fid.scale.max: 10
        wtf.zhulik.fid.timeout: 10

volumes:
  nats_data:
