services:
  proxy:
    image: fid-proxy
    build:
      context: .
      args:
        COMPONENT: "proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "proxy"
      replicas: 1
    ports:
      - 80:80

  wsserver:
    image: fid-wsserver
    build:
      context: .
      args:
        COMPONENT: "wsserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "wsserver"
      replicas: 1

    ports:
      - 81:80

  infoserver:
    image: fid-infoserver
    build:
      context: .
      args:
        COMPONENT: "infoserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "infoserver"
      replicas: 1

    ports:
      - 82:80

  function:
    image: function
    build:
      context: .
      args:
        COMPONENT: "function"

    environment:
      - WS_URI=ws://wsserver/function

    deploy:
      labels:
        wtf.zhulik.fid.component: "function"
        wtf.zhulik.fid.scale.min: 3
        wtf.zhulik.fid.scale.max: 10
      replicas: 1

    depends_on:
      - wsserver
      - proxy
