services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - /tmp/nats/:/data
    command: [ "-js" ]
    networks:
      - nats

  # Does not exist yet
  init:
    image: ghcr.io/zhulik/fid-init
    build:
      context: .
      args:
        COMPONENT: "init"
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./functions.yaml:/functions.yaml

    networks:
      - nats

    depends_on:
      - nats

volumes:
  nats_data:

networks:
  nats:
    name: nats
    driver: bridge
