services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - /tmp/nats/:/data
    command: [ "-js" ]

  gateway:
    image: fid/gateway
    build:
      context: .
      args:
        COMPONENT: "gateway"
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "gateway"
      replicas: 1
    ports:
      - 80:80

  forwarder:
    image: fid/forwarder
    build:
      context: .
      args:
        COMPONENT: "forwarder"

    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "forwarder"
      replicas: 1

    ports:
      - 81:80

  infoserver:
    image: fid/infoserver
    build:
      context: .
      args:
        COMPONENT: "infoserver"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        wtf.zhulik.fid.component: "infoserver"
      replicas: 1

    ports:
      - 82:80

  function:
    image: fid/demo-function
    build:
      context: .
      args:
        COMPONENT: "function"

    environment:
      - WS_URI=ws://forwarder/ws/function

    deploy:
      labels:
        wtf.zhulik.fid.component: "function"
        wtf.zhulik.fid.scale.min: 3
        wtf.zhulik.fid.scale.max: 10
      replicas: 1

    depends_on:
      - forwarder

volumes:
  nats_data:
