services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - /tmp/nats/:/data
    command: [ "-js" ]
    networks:
      - nats

  init:
    image: ghcr.io/zhulik/fid-init
    build:
      context: .
      args:
        COMPONENT: "init"
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./functions.yaml:/functions.yaml
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - nats

    depends_on:
      - nats

    restart: no

volumes:
  nats_data:

networks:
  nats:
    name: nats
    driver: bridge
