version: '3'
tasks:
  default:
    cmds:
      - task: check
      - task: build

  check:
    cmds:
      - task: lint
      - task: test

  lint_fix:
    deps:
      - mocks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix

  lint:
    deps:
      - mocks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run

  test:
    deps:
      - env
      - mocks
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo run -r -race

  build:
    vars:
      COMPONENTS:
        - init
        - gateway
        - runtimeapi
        - infoserver
        - scaler
        - demo-function
    cmds:
      - |
        {{range $index, $component := .COMPONENTS}}
          docker buildx build --build-arg COMPONENT={{ $component }} -t ghcr.io/zhulik/fid-{{ $component }} . &
        {{end}}
        wait

  env:
    deps:
      - nats

  nats:
    cmds:
      - docker compose up -d nats

  mocks:
    cmds:
      - go tool github.com/vektra/mockery/v2

  down:
    cmds:
      - docker kill $(docker ps -q)

  init:
    deps:
      - nats
      - build
    cmds:
      - docker compose up -d init

  restart:
    cmds:
      - task: down
      - task: init
