version: '3'
tasks:
  default:
    cmds:
      - task: check
      - task: build

  check:
    cmds:
      - task: lint
      - task: test

  lint_fix:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix

  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run

  test:
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo run -r -race

  build:
    cmds:
      - task: build_components

  build_components:
    cmds:
      - |
        for component in init gateway runtimeapi infoserver scaler demo-function; do
          docker buildx build --build-arg COMPONENT=$component -t ghcr.io/zhulik/fid-$component . &
        done
        wait