version: '3'
tasks:
  default:
    cmds:
      - task: check
      - task: build

  check:
    cmds:
      - task: lint
      - task: test

  lint_fix:
    deps:
      - mocks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix

  lint:
    deps:
      - mocks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run

  test:
    deps:
      - env
      - mocks
    cmds:
      - go run github.com/onsi/ginkgo/v2/ginkgo run -r -race

  build:
    cmds:
      - docker buildx build --build-arg COMPONENT=demo-function -t ghcr.io/zhulik/fid-demo-function .
      - docker buildx build --build-arg COMPONENT=fid -t ghcr.io/zhulik/fid .

  env:
    deps:
      - nats

  nats:
    cmds:
      - docker compose up -d nats

  mocks:
    cmds:
      - go tool github.com/vektra/mockery/v2

  down:
    cmds:
      - docker kill $(docker ps -q)

  init:
    deps:
      - nats
      - build
    cmds:
      - docker compose up -d init

  restart:
    cmds:
      - task: down
      - task: init
