on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Setup task
        run: go install github.com/go-task/task/v3/cmd/task@v3.41.0

      - name: Download dependencies
        run: go mod download

      - name: Run linter
        run: task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Setup task
        run: go install github.com/go-task/task/v3/cmd/task@v3.41.0

      - name: Start NATS
        run: docker compose up -d nats

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: task test

# TODO: build and push Docker images
